image:
  file: .gitpod.Dockerfile
tasks:
  - init: |
      ./gitpod-init.sh
  - command: |
      ./gitpod-command.sh
      pyenv activate search_with_ml
  - env:
      FLASK_ENV: development
      PRIOR_CLICKS_LOC: /workspace/ltr_output/train.csv
      FLASK_APP: week2
ports:
  - port: 3000
    onOpen: ignore
  - port: 5000
    onOpen: ignore
  - port: 5001
    onOpen: ignore
  - port: 5601
    onOpen: open-browser
  - port: 9200
    onOpen: ignore
  - port: 9300
    onOpen: ignore
  - port: 9000
    onOpen: ignore
  - port: 9003
    onOpen: ignore
  - port: 9004
    onOpen: ignore
  - port: 9600
    onOpen: ignore
  - port: 9601
    onOpen: ignore
  - port: 9602
    onOpen: ignore